<robot xmlns:xacro="http://ros.org/wiki/xacro" name="bandit">
    <material name="brick">
        <color rgba="0.5 0.125 0.13 1"/>
    </material>
    
    <!-- Defining properties for the torso support -->
    <xacro:property name="SupportHeight" value="1.25" />
    <xacro:property name="SupportDepth"  value="0.16" />
    <xacro:property name="SupportWidth"  value="1" />
    <xacro:property name="SupportSize"   value="${SupportWidth} ${SupportDepth} ${SupportHeight}" />
    <xacro:property name="SupportOrigin" value="0 0 -${ SupportHeight / 2}" />
    <xacro:property name="SupportOrientation" value="0 0 0" />
    <xacro:property name="SupportMass"   value="1000000" />

    <xacro:macro name="make_support" params="parent_link link_name">
        <link name="${link_name}">
            <visual>
                <origin rpy="${SupportOrientation}" xyz="${SupportOrigin}"/>
                <geometry>
                    <box size="${SupportSize}"/>
                </geometry>
                <material name="brick"/>
            </visual>
            <inertial>
                <mass value="${SupportMass}"/>
                <origin rpy="${SupportOrientation}" xyz="${SupportOrigin}"/>
                <inertia ixx="${ SupportMass/12 * (SupportDepth*SupportDepth + SupportHeight*SupportHeight) }" 
                         ixy="0" 
                         ixz="0" 
                         iyy="${ SupportMass/12 * (SupportWidth*SupportWidth + SupportHeight*SupportHeight) }" 
                         iyz="0" 
                         izz="${ SupportMass/12 * (SupportDepth*SupportDepth + SupportWidth*SupportWidth) }"
                />
            </inertial>
            <collision>
                <origin rpy="${SupportOrientation}" xyz="${SupportOrigin}"/>
                <geometry>
                    <box size="${SupportSize}"/>
                </geometry>            
            </collision>
        </link>
    
        <gazebo reference="${link_name}">
            <material>
                Gazebo/Bricks
            </material>
        </gazebo>
    
        <joint name="${link_name}_joint" type="fixed">
            <parent link="${parent_link}"/>
            <child link="${link_name}"/>
            <origin rpy="0.0 0.0 1.57" xyz="0.0 0.0 0.0"/>
        </joint>
    </xacro:macro>
</robot>
